config/routes.rb
Rails.application.routes.draw do

  root "events#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :index]
  resources :events, only: [:new, :create, :edit,:show, :index] do 
    member do
      get 'rsvp'
      get 'cancel_rsvp'
    end
  end



  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, :foreign_key => "creator_id", class_name: 'User'
    has_many :rsvps, :foreign_key => "attended_event_id"
    has_many :attendees, through: :rsvps

end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
    belongs_to :attendee, class_name: "User"
    belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :created_events, :foreign_key => "creator_id", class_name: "Event"
    has_many :rsvps, :foreign_key => "attendee_id"
    has_many :attended_events, through: :rsvps
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user
        return unless session[:user_id]
        @current_user ||= User.find(session[:user_id])
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        @events = Event.all.order("created_at DESC")
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.created_events.build(event_params)
        

        if @event.save
            redirect_to root_path
        else
            render :new
        end
    end

    def show
        @event = Event.find(params[:id])
    end

    def edit
        @event = Event.find(params[:id])
    end

    def rsvp
        @event = Event.find(params[:id])
        if @event.attendees.include?(current_user)
            redirect_to @event, notice: "You're already going!"
        else
            @event.attendees << current_user
            redirect_to @event
        end
    end

    private

    def event_params
        params.require(:event).permit(:title, :description, :date, :location)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        @user = User.find_by(username: params[:username])

        if @user
            session[:user_id] = @user.id
            redirect_to root_path
        else
            message = "Something went wrong!  Check your username and password are correct."
            redirect_to login_path, notice: message
        end
    end

    def destroy
       session[:user_id] = nil
       redirect_to root_path, notice: "logged out!" 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render :new 
        end
        
    end

    def edit
        @event = User.find(params[:id])
    end

    def show
        @user = User.find(params[:id])
    end

    def rsvp
        @event = Event.find(params[:id])
        if @event.attendees.include?(current_user)
            redirect_to @event, notice: "You're already going!"
        else
            @event.attendees << current_user
            redirect_to @event
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def logged_in?
        !!session[:user_id]
    end

    def current_user
       @current_user = User.find_by_id(session[:user_id]) 
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<% if logged_in? %>
    <% current_user.created_events.each do |event| %> 


        <div>
        <br> <%= event.title%> <br>
        </div>
        <div>
            <%= event.date %> <br>
        </div>
        <div>
        <%= event.location %> <br>
        </div>

    <% end %>
<% end %>

app/views/events/edit.html.erb
<br>
<%= form_with model: Event do |form| %>
<%= form.label :title %>
<%= form.text_field :title, placeholder: "Event name" %>  <br>
<%= form.label :description %>
<%= form.text_field :description, placeholder: "Write about your event here!" %>  <br>
<%= form.label :location %>
<%= form.text_field :location, placeholder: "Where are we going?!" %>  <br>
<%= form.label :date %>
<%= form.date_field :date %>  <br>
<%= form.submit "Submit"%>
<% end %>

app/views/events/index.html.erb
<h1>Welcome to the event planner</h1>

<% if logged_in? %>
    <%= current_user.email %>

<% end %>
<br>
<%= render "event" %>
<br>

<%= link_to "New Event!", new_event_path%>


<br>
<%= link_to "New User", new_user_path %>
<br>
<%= link_to "Log In", login_path%>
<br>
<%= link_to "log out", logout_path %>

<br>
<h3> Look at all these upcoming events! </h3>  <br>


    <% @events.each do |event| %> 


        <div>
        <br> <%= link_to event.title, event_path(event) %> <br>
        </div>
        <div>
            <%= event.date %> <br>
        </div>
        <div>
        <%= event.location %> <br>
        </div>
        

    <% end %>

app/views/events/new.html.erb
<br>
<%= form_with model: Event.new do |form| %>
<%= form.label :title %>
<%= form.text_field :title, placeholder: "Event name" %>  <br>
<%= form.label :description %>
<%= form.text_field :description, placeholder: "Write about your event here!" %>  <br>
<%= form.label :location %>
<%= form.text_field :location, placeholder: "Where are we going?!" %>  <br>
<%= form.label :date %>
<%= form.date_field :date %>  <br>
<%= form.submit "Submit"%>
<% end %>

app/views/events/show.html.erb
<h1>Event Details</h1> <br>

<h2> <%= @event.title %> <br> </h2>
<%= @event.location %> <br>
<%= @event.date %> <br>
Hosted by: <%= @event.creator.username %> <br>


<% if current_user == @event.creator %>
    <%= link_to 'Edit', edit_event_path %>

<% else %>

<%= link_to 'RSVP', rsvp_event_path %>
<% end %>

<br> <br>

<% if @event.attendees.count == 0 %>
    This event has no one going yet.  Why not be the first?!
<% else %>
    Attendees: 
    <br>
    <% @event.attendees.each do |attendee| %>
    <%= attendee.username %>
    <% end %>
<% end %>

<br>
<br>
<%= link_to 'Home Page', root_path %>

app/views/layouts/_nav.html.erb
<span>
    <br>
    <% if logged_in? %>
        <%= link_to 'My Events', user_path(current_user)%>
        <%= link_to 'logout', logout_path %>
    <% end %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventPlanner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/nav' %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Welcome to the event planner</h1>

<% if logged_in? %>
    <%= current_user.email %>

<% end %>
<%= @events.each do |event| %>
<%= event.title%> <br>
<%= event.date %> <br>
<%= event.location %> <br>
<% end %>

<%= link_to "New Event!", new_event_path%>


<br>
<%= link_to "New User", new_user_path %>
<br>
<%= link_to "Log In", login_path%>
<br>
<%= link_to "log out", logout_path %>

app/views/users/new.html.erb
<br>
<%= form_with model: User.new do |form| %>
<%= form.label :username %>
<%= form.text_field :username, placeholder: "Username" %>  <br>
<%= form.label :email %>
<%= form.text_field :email, placeholder: "Email@yourmom.com" %>  <br>
<%= form.label :password %>
<%= form.text_field :password, placeholder: "Password" %>  <br>
<%= form.submit "Submit"%>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.username %> </h1>

<br>

<h3> is hosting... </h3> <br>
<div>
    <% if @user.created_events.count > 0 %>
        <% @user.created_events.each do |event|  %>
        <%= event.title%> <br>
        <%= event.date %> <br>
        <%= event.location %> <br>
        <%end%>
    <% else %>
        nothing :(
    <% end %>
</div>



<h3> has attended... </h3> <br>
<div>
    <% if @user.attended_events.count > 0 %>
        <% @user.attended_events.each do |event|  %>
            <% if event.date < Time.now %>
                <%= event.title%> <br>
                <%= event.date %> <br>
                <%= event.location %> <br>
            <%end%>
        <%end%>
    <% else %>
        nothing :(
    <% end %>
</div>

<h3> is attending... </h3> <br>


<div>
    <% if @user.attended_events.count > 0 %>
        <% @user.attended_events.each do |event|  %>
            <% if event.date > Time.now %>
                <%= event.title%> <br>
                <%= event.date %> <br>
                <%= event.location %> <br>
            <%end%>
        <%end%>
    <% else %>
        nothing :(
    <% end %>
</div>